version: "3.8"

services:
  stats-db:
    image: postgres:16.1
    container_name: stats-db-container
    ports:
      - "9542:5432"
    depends_on:
      - ewm-db
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=stats_admin
      - POSTGRES_DB=stats
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stats_admin -d stats"]
      interval: 10s
      retries: 5
      timeout: 5s

  stats-server:
    build:
      context: ./stat/stat-service
      dockerfile: Dockerfile
    image: stat-service-image
    container_name: stat-service-container
    ports:
      - "9090:9090"
      - "9001:9001"
    depends_on:
      stats-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=stats_admin
      - SPRING_DATASOURCE_PASSWORD=12345
      - JAVA_OPTS=-Xms256m -Xmx512m

  ewm-db:
    image: postgres:16.1
    container_name: ewm-db-container
    ports:
      - "8542:5432"
    environment:
      - POSTGRES_PASSWORD=u$ErSP@$$
      - POSTGRES_USER=ewm_admin
      - POSTGRES_DB=ewm
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ewm_admin -d ewm"]
      interval: 10s
      retries: 5
      timeout: 5s

  ewm-service:
    build:
      context: ./main-service
      dockerfile: Dockerfile
    image: ewm-service-image
    container_name: ewm-service-container
    ports:
      - "8080:8080"
      - "8001:8001"
    depends_on:
      ewm-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - SPRING_DATASOURCE_USERNAME=ewm_admin
      - SPRING_DATASOURCE_PASSWORD=u$ErSP@$$
      - JAVA_OPTS=-Xms256m -Xmx512m
